name: vicast
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9

  # VICAST-annotate essentials
  - biopython
  - pandas
  - numpy

  # Pathway 3: BLASTx annotation (flexible version - 2.13+ works fine)
  - blast

  # SnpEff (may need manual upgrade to 5.2+ for Java 21)
  - snpeff

  # Utilities
  - pip

  - pip:
    - argparse

# Note: This is a minimal environment for VICAST-annotate only.
# For full VICAST (with variant calling), use environment.yml instead.
#
# Why minimal?
# - Faster to create (fewer packages = less memory during solve)
# - Only includes packages needed for annotation pipelines
# - Full environment.yml includes variant calling tools (bwa, samtools, etc.)
#
# Manual installations:
# - SnpEff 5.2+ with Java 21 (optional): bash setup/install_java21_conda.sh
# - BLAST databases: Download from https://ftp.ncbi.nlm.nih.gov/blast/db/
