name: vicast
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9

  # VICAST-annotate (all pathways need these)
  - biopython
  - pandas
  - numpy
  - matplotlib
  - pyyaml

  # Pathway 3: BLASTx annotation
  - blast

  # Pathway 2 QC: Gap detection and ORF finding
  - emboss

  # SnpEff for variant annotation
  - snpeff

  # Report generation (Pathway 2 QC)
  - markdown         # Markdown to HTML conversion
  - weasyprint       # HTML to PDF conversion

  # VICAST-analyze: Variant calling tools (can be omitted for annotation-only)
  - bwa
  - samtools
  - bcftools
  - megahit
  - lofreq
  - fastp
  - seqkit

  # Utilities
  - entrez-direct  # For NCBI downloads
  - pip

  - pip:
    - argparse
    - tabulate

# Additional manual installations required:
#
# SnpEff 5.2+ with Java 21:
#   - For latest SnpEff features and better performance
#   - Run: bash setup/install_java21_conda.sh
#
# BLAST databases (Pathway 3):
#   - Download nr, refseq_protein, or custom viral database
#   - See: https://ftp.ncbi.nlm.nih.gov/blast/db/
#   - Or use smaller viral-specific database for faster searches