name: vicast_analyze
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9

  # Core analysis libraries
  - biopython
  - pandas
  - numpy
  - matplotlib
  - pyyaml

  # Read alignment and processing
  - bwa
  - samtools
  - bcftools

  # Quality control and preprocessing
  - fastp
  - fastqc
  - multiqc

  # Variant calling
  - lofreq        # Low-frequency variant caller
  - freebayes     # Alternative variant caller
  - vcftools      # VCF manipulation

  # Assembly (for de novo if needed)
  - megahit
  - spades

  # Sequence utilities
  - seqkit
  - seqtk

  # SnpEff for variant annotation
  - snpeff

  # Coverage analysis
  - bedtools
  - mosdepth

  # Data retrieval
  - entrez-direct

  # Utilities
  - pip

  - pip:
    - argparse
    - tabulate
    - pysam

# VICAST-analyze: Variant calling pipeline for cultured virus passage studies
#
# Use this environment for:
# - Read mapping to reference genomes
# - Low-frequency variant detection
# - Tracking evolutionary changes across passages
# - Coverage analysis
# - Assembly validation
#
# For annotation only (Pathways 1-4), use environment_vicast_annotate.yml instead
#
# Manual installations required:
# - SnpEff 5.2+ with Java 21 (optional): bash setup/install_java21_conda.sh
# - Reference genomes: Prepare from vicast-annotate or NCBI
