name: vicast
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python
  - python>=3.8

  # VICAST-annotate essentials
  - biopython
  - pandas
  - numpy

  # Pathway 3: BLASTx annotation
  - blast>=2.15.0

  # Pathway 4: Segmented viruses (uses same tools)

  # SnpEff (may need manual upgrade to 5.2+ for Java 21)
  - snpeff

  # Utilities
  - pip

  - pip:
    - argparse

# Note: This is a minimal environment for VICAST-annotate only.
# For full VICAST (with variant calling), use environment.yml instead.
#
# Manual installations:
# - SnpEff 5.2+ with Java 21 (optional): bash setup/install_java21_conda.sh
# - BLAST databases: Download from https://ftp.ncbi.nlm.nih.gov/blast/db/
