name: vicast_annotate
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9

  # VICAST-annotate essentials
  - biopython
  - pandas
  - numpy

  # Pathway 3: BLASTx annotation (flexible version - 2.13+ works fine)
  - blast

  # Pathway 2 QC: Gap detection and ORF finding
  - emboss

  # SnpEff (may need manual upgrade to 5.2+ for Java 21)
  - snpeff

  # Report generation (Pathway 2 QC)
  - python-markdown  # Markdown to HTML conversion
  - weasyprint       # HTML to PDF conversion

  # Utilities
  - pip

  - pip:
    - argparse

# VICAST-annotate: Genome annotation pipelines (Pathways 1-4)
#
# Use this environment for:
# - Adding poorly annotated viral genomes to SnpEff databases
# - BLASTx-based homology annotation
# - Polyprotein curation and quality control
# - Segmented virus handling
#
# For variant calling, use environment_vicast_analyze.yml instead
# For everything (annotation + variant calling), use environment.yml
#
# Manual installations:
# - SnpEff 5.2+ with Java 21 (optional): bash setup/install_java21_conda.sh
# - BLAST databases: Download from https://ftp.ncbi.nlm.nih.gov/blast/db/
