name: viral_genomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - biopython=1.79
  - pandas
  - numpy
  - boost=1.74
  # Note: BLAST will be used from /ref/sahlab/software/ncbi-blast-2.10.0+/bin
  # No need to install in conda environment
  - pip
  - pip:
    - python-dateutil
